kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller-rolebinding
subjects:
  - kind: ServiceAccount
    name: crd-controller
roleRef:
  kind: Role
  name: config-monitor-crd
  apiGroup: rbac.authorization.k8s.io